# Generated by Django 4.2.30 on 2026-06-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('environmental', 'Environmental'), ('animal_welfare', 'Animal Welfare'), ('community', 'Community'), ('governance', 'Governance'), ('economic', 'Economic'), ('research', 'Research'), ('transparency', 'Transparency'), ('annual', 'Annual')], max_length=30)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='regions.region')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReportSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='reports.report')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to='sources.source')),
            ],
            options={
                'verbose_name': 'Report Source Link',
                'verbose_name_plural': 'Report Source Links',
                'unique_together': {('report', 'source')},
            },
        ),
    ]
