# Generated by Django 4.2.30 on 2026-06-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('region_type', models.CharField(choices=[('country', 'Country'), ('state', 'State / Province'), ('district', 'District'), ('city', 'City')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geojson_boundary', models.JSONField(blank=True, null=True)),
                ('current_ghi_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_status', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('estimated', 'Estimated'), ('placeholder', 'Placeholder'), ('archived', 'Archived')], default='placeholder', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_regions', to='regions.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
