# Generated by Django 4.2.30 on 2026-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('research', 'Research'), ('international', 'International'), ('news', 'News'), ('academic', 'Academic'), ('foundation', 'Foundation'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['-publication_date', 'title'],
            },
        ),
    ]
