# Generated by Django 4.2.30 on 2026-06-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('entity_type', models.CharField(choices=[('organization', 'Organization'), ('ngo', 'NGO'), ('activist', 'Activist'), ('company', 'Company'), ('product', 'Product'), ('initiative', 'Initiative'), ('project', 'Project'), ('event', 'Event')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.URLField(blank=True, max_length=1000)),
                ('website', models.URLField(blank=True, max_length=1000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned'), ('archived', 'Archived')], default='active', max_length=30)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('unverified', 'Unverified'), ('pending', 'Pending Review')], default='unverified', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_entities', to='regions.region')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityRegionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('operates_in', 'Operates In'), ('headquartered_in', 'Headquartered In'), ('supports', 'Supports'), ('impacts', 'Impacts')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_links', to='entities.entity')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='regions.region')),
            ],
            options={
                'verbose_name': 'Entity Region Link',
                'verbose_name_plural': 'Entity Region Links',
                'unique_together': {('entity', 'region', 'relationship_type')},
            },
        ),
    ]
