# Generated by Django 4.2.30 on 2026-06-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghicategory',
            options={'ordering': ['name'], 'verbose_name': 'GHI Category', 'verbose_name_plural': 'GHI Categories'},
        ),
        migrations.CreateModel(
            name='GHIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='Example: AQI, %, INR, years, count', max_length=100)),
                ('direction', models.CharField(choices=[('higher_is_better', 'Higher is better'), ('lower_is_better', 'Lower is better'), ('target_range', 'Target range'), ('binary', 'Binary'), ('composite', 'Composite')], max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ghi.ghicategory')),
            ],
            options={
                'verbose_name': 'GHI Metric',
                'verbose_name_plural': 'GHI Metrics',
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
