# Generated by Django 4.2.30 on 2026-06-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghi', '0002_alter_ghicategory_options_ghimetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Methodology Version',
                'verbose_name_plural': 'Methodology Versions',
                'ordering': ['-published_date'],
            },
        ),
    ]
