# Generated by Django 4.2.30 on 2026-06-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghi', '0003_methodologyversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('linear', 'Linear'), ('inverse_linear', 'Inverse Linear'), ('target_range', 'Target Range'), ('binary', 'Binary'), ('custom_formula', 'Custom Formula')], max_length=30)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('formula', models.TextField(blank=True, help_text='Optional formula notes or future calculation expression.')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_rules', to='ghi.methodologyversion')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_rules', to='ghi.ghimetric')),
            ],
            options={
                'verbose_name': 'Conversion Rule',
                'verbose_name_plural': 'Conversion Rules',
                'ordering': ['metric__category__name', 'metric__name', '-created_at'],
            },
        ),
    ]
