# Generated by Django 4.2.30 on 2026-06-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('sources', '0001_initial'),
        ('ghi', '0004_conversionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('estimated', 'Estimated')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='ghi.ghimetric')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='regions.region')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_values', to='sources.source')),
            ],
            options={
                'verbose_name': 'Metric Value',
                'verbose_name_plural': 'Metric Values',
                'ordering': ['-year', 'region__name', 'metric__name'],
            },
        ),
    ]
