# Generated by Django 4.2.30 on 2026-06-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('ghi', '0005_metricvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_scores', to='ghi.ghimetric')),
                ('metric_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ghi.metricvalue')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_scores', to='regions.region')),
            ],
            options={
                'verbose_name': 'Metric Score',
                'verbose_name_plural': 'Metric Scores',
                'ordering': ['region__name', 'metric__name'],
            },
        ),
    ]
