# Generated by Django 4.2.30 on 2026-06-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('ghi', '0006_metricscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHIScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('environmental_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('human_wellbeing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('animal_welfare_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('community_health_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('economic_stability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('governance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_completeness', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of required data available.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('methodology_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ghi_score_snapshots', to='ghi.methodologyversion')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghi_score_snapshots', to='regions.region')),
            ],
            options={
                'verbose_name': 'GHI Score Snapshot',
                'verbose_name_plural': 'GHI Score Snapshots',
                'ordering': ['-year', 'region__name'],
                'unique_together': {('region', 'year', 'methodology_version')},
            },
        ),
    ]
